name: 股票期权数据扫描

on:
  schedule:
    # 美国西部时间 (PST/PDT) 周一到周五
    # 冬季时间 (PST = UTC-8): 5:30 AM PST = 13:30 UTC
    # 夏季时间 (PDT = UTC-7): 5:30 AM PDT = 12:30 UTC
    # 使用两个 cron 表达式覆盖冬夏两季
    - cron: '30 12,13,14,15,16,17,18,20 * * 1-5'  # 夏季时间 (PDT)
    - cron: '30 13,14,15,16,17,18,19,21 * * 1-5'  # 冬季时间 (PST)
  workflow_dispatch:  # 允许手动触发

jobs:
  scan-stocks:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas numpy xlsxwriter
        
    - name: 运行股票期权扫描
      run: |
        echo "开始扫描股票期权数据..."
        python scan_stock_30min.py --max-stocks 50 --delay 0.5
        echo "扫描完成"
        
    - name: 提交数据文件
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add option_data/ stock_price/
        if git diff --staged --quiet; then
          echo "没有新的数据文件需要提交"
        else
          git commit -m "Auto-update: 股票期权数据 $(date '+%Y-%m-%d %H:%M')"
          git push
        fi
