name: 完整股票分析流程 (扫描+异常检测)

on:
  schedule:
    # 使用更精确的时间配置，考虑夏令时
    # 美国西部时间 (PST/PDT) 周一到周五
    # 5:30, 6:30, 7:30, 8:30, 9:30, 10:30, 11:30, 13:30
    - cron: '30 12,13,14,15,16,17,18,20 * * 1-5'  # 覆盖夏季时间
    - cron: '30 13,14,15,16,17,18,19,21 * * 1-5'  # 覆盖冬季时间
  workflow_dispatch:  # 允许手动触发

jobs:
  scan-stocks:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas numpy xlsxwriter
        
    - name: 检查当前时区
      run: |
        echo "当前 UTC 时间: $(date -u)"
        echo "当前本地时间: $(date)"
        echo "检查是否在夏令时期间..."
        # 简单的夏令时检查：3月第二个周日到11月第一个周日
        python3 -c "
        import datetime
        now = datetime.datetime.now()
        # 2024年夏令时：3月10日 - 11月3日
        # 2025年夏令时：3月9日 - 11月2日
        dst_start_2024 = datetime.datetime(2024, 3, 10)
        dst_end_2024 = datetime.datetime(2024, 11, 3)
        dst_start_2025 = datetime.datetime(2025, 3, 9)
        dst_end_2025 = datetime.datetime(2025, 11, 2)
        
        is_dst = (dst_start_2024 <= now < dst_end_2024) or (dst_start_2025 <= now < dst_end_2025)
        print(f'是否在夏令时期间: {is_dst}')
        print(f'当前年份: {now.year}')
        print(f'当前月份: {now.month}')
        print(f'当前日期: {now.day}')
        "
        
    - name: 下载历史数据文件
      uses: actions/download-artifact@v4
      with:
        name: stock-data
        path: ./data
      continue-on-error: true
      
    - name: 准备历史数据
      run: |
        if [ -d "./data/option_data" ]; then
          echo "找到历史期权数据，复制到当前目录"
          cp -r ./data/option_data/* ./option_data/ 2>/dev/null || true
        fi
        if [ -d "./data/stock_price" ]; then
          echo "找到历史股票价格数据，复制到当前目录"
          cp -r ./data/stock_price/* ./stock_price/ 2>/dev/null || true
        fi
        echo "当前期权数据文件："
        ls -la option_data/ || echo "期权数据目录为空"
        echo "当前股票价格数据文件："
        ls -la stock_price/ || echo "股票价格数据目录为空"
        
    - name: 运行股票期权扫描
      run: |
        echo "开始扫描股票期权数据..."
        python scan_stock_30min.py --max-stocks 10 --delay 0.5
        echo "扫描完成"
        
    - name: 运行持仓量异常检测
      run: |
        echo "开始持仓量异常检测..."
        cd program
        python find_outliers_by_oi.py
        echo "持仓量异常检测完成"
        
    - name: 运行成交量异常检测
      run: |
        echo "开始成交量异常检测..."
        cd program
        python find_outliers_by_volume.py
        echo "成交量异常检测完成"
        
    - name: 上传数据文件到 Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: stock-data
        path: |
          option_data/
          stock_price/
          outlier/
          volume_outlier/
        retention-days: 30
        
    - name: 提交所有数据文件
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add option_data/ stock_price/ outlier/ volume_outlier/
        if git diff --staged --quiet; then
          echo "没有新的数据文件需要提交"
        else
          git commit -m "Auto-update: 完整股票分析数据 $(date '+%Y-%m-%d %H:%M') [$(date '+%Z')]"
          git push
        fi
